### ISSUE TITLE
Проблема с ининцализацией

### ISSUE THREAD

**Issue by mdorfin** [ilyabirman/Likely#11] opened 2015-12-06 12:08 UTC
Иногда виджет инициализируется только после перезагрузки страницы
Например http://www.eyeseestyle.com/en/diary/big-geometric-earrings внизу поста.

**Comment by volter9** [comment] 2015-12-06 12:14
English, please :) 

I don't really see the problem, could you elaborate what the problem is?

**Comment by volter9** [comment] 2015-12-08 13:33
No response for few days. Is your issue already solved?

**Comment by volter9** [comment] 2015-12-09 18:18
I don't see the issue, and you seem to solve your issue too. I'll close the issue, then.

**Closed by volter9** 2015-12-09 18:18 UTC

**Comment by mdorfin** [comment] 2015-12-10 04:54
Sorry, it was a problem with initialization. The fix is remove turbolinks gem from the project. :)
